apiVersion: v1
kind: Service
metadata:
  name: actor-service
  labels:
    main: docker-kubernetes-project
    app: actor-k8s-application
    project: actor
spec:
  selector:
    project: actor
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  externalIPs:
    - 80.11.12.10