apiVersion: v1
kind: Service
metadata:
  name: director-service
  labels:
    main: docker-kubernetes-project
    app: director-k8s-application
    project: director
spec:
  selector:
    project: director
  type: NodePort
  ports:
    - port: 80
      targetPort: 8084
      protocol: TCP
  externalIPs:
    - 80.11.12.14