apiVersion: v1
kind: PersistentVolume
metadata:
  name: activemq-pv-volume
  labels:
    main: docker-kubernetes-project
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-pv-claim
  labels:
    main: docker-kubernetes-project
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi