apiVersion : apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  labels:
    main: docker-kubernetes-project
    app: movie-k8s-application
spec:
  selector:
    matchLabels:
      project: movie
  template:
    metadata:
      labels:
        project: movie
    spec:
      containers:
        - name: movie-web
          image: yeshenko/movie-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: postgresql-secret
            - secretRef:
                name: activemq-secret
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /datasets
              name: file
      volumes:
        - name: file
          hostPath:
            path: /docker-kubernetes/datasets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movie-autoscaling
  labels:
    main: docker-kubernetes-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70